swagger: '2.0'
info:
  description: API to access smart home devices in your local network
  version: 1.0.0
  title: MySmartHome
  termsOfService: ''
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - http
paths:
  /devices:
    get:
      tags:
        - devices
      summary: show all devices
      description: ''
      operationId: listDevices
      produces:
        - application/json
      responses:
        '200':
          description: list
  '/devices/{deviceId}':
    get:
      tags:
        - devices
      summary: Find device by ID
      description: Returns device info
      operationId: getDeviceById
      produces:
        - application/json
      parameters:
        - name: deviceId
          in: path
          description: ID of device to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Device not found
    put:
      tags:
        - devices
      summary: Updates a device
      description: ''
      operationId: updateDeviceWithForm
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: deviceId
          in: path
          description: ID of device that needs to be updated
          required: true
          type: string
      responses:
        '405':
          description: Invalid input
  '/devices/{deviceId}/request':
    post:
      tags:
        - request
      summary: forward a request to the device
      description: Returns the response of the device
      operationId: request
      produces:
        - application/json
      parameters:
        - name: deviceId
          in: path
          description: ID of device
          required: true
          type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Device not found
